Financial-Times/o-header-services

bower.json, demos/src/no-navigation.mustache, demos/src/one-navigation.mustache, src/scss/_drawer.scss
Bumps the version of `o-header` which adds the visually hidden mixin and implements the class here. Also corrects a typo in the classnames for demos.
=> Fix drawer close

README.md, demos/src/no-navigation.mustache, demos/src/one-navigation.mustache, demos/src/themes.mustache, demos/src/very-simple.mustache, src/scss/_top.scss
Adds text to the drawer button for accessibility (visually hidden).
Adds styles to allow for links in the product title tag and updates examples and readme.
=> A11y and link in product title

README.md, bower.json, demos/src/themes.mustache, demos/src/two-navigation.mustache, main.scss, origami.json, src/scss/_colors.scss, src/scss/_secondary_nav.scss
This PR adds in the subnav from o-header, which is needed by the KMT team. I've also made some small fixes in the README
=> Add subnav

src/scss/_top.scss, src/scss/_variables.scss
This enforces logos from the ftlogo image set to be used, and allows more succint logo names in products using the `oHeaderServiceTop` mixin (e.g. `o-layout`)
=> update logo url

src/scss/_drawer.scss
:mask: Unlike `o-header`, the README and demos for `o-header-serivces` say to include ".o--if-js" on the draw. However ".core .o--if-js" may be repalced with ".enhanced .o--if-js" before "data-o-header-drawer--js" is added. This causes a flash where the draw is rendered before being positioned. So, only display the draw when "data-o-header-drawer--js" has been added by o-header.
I believe this is what causes the flash when navigating  `o-layout` sites *:warning: gif flashes*:
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
=> Only display the draw when "data-o-header-drawer--js" has been added by `o-header` JS.

README.md, main.scss, src/scss/_base.scss, src/scss/_brand.scss, src/scss/_drawer.scss, src/scss/_primary-nav.scss, src/scss/_secondary-nav.scss, src/scss/_theme.scss, src/scss/_top.scss, src/scss/_variables.scss
After having a conversation with Tom Dew, who is working on FDi, and seeing his implementation of a header, this PR adds whitelabel specific support (which was missing anyway). 
It looks like this:
Again,  README + MIGRATION are left for last when V3 is ready
=> Add whitelabel

MIGRATION.md, README.md, demos/src/header.mustache, main.scss, origami.json, src/scss/_functions.scss, src/scss/_top.scss
Last but not least, this PR updates the README and the MIGRATION.md
It also makes a change to the way in which the logo is implemented, allowing for a string with the logo name or a full url to be passed in to the primary mixin's `$opts`.
=> Documentation & customisation update

src/scss/_functions.scss
This allows a user of o-header-services to use url-relative paths for their logo. This feature was requested by the Origami team for use on the polyfill.io service.
=> Enable relative url support for custom logos

src/scss/_drawer.scss, src/scss/_top.scss
Updating some padding that is broken on mobile, and the position of the header that is broken if it is used with `o-layout`
=> tiny nudges

src/scss/_functions.scss
They should have their logo returned as-is, currently the bug makes the function return the origami-image-service url instead.
=> Fix bug where path relative logos would get returned the wrong string.

MIGRATION.md, README.md, demos/src/header.mustache, main.scss, origami.json, src/js/drawer.js, src/scss/_base.scss, src/scss/_brand.scss, src/scss/_drawer.scss, src/scss/_drop-down.scss, src/scss/_primary-nav.scss, src/scss/_secondary-nav.scss, src/scss/_theme.scss, src/scss/_top.scss, src/scss/_variables.scss, test/helpers/fixtures.js, test/js/drawer.test.js, test/js/drop-down.test.js
- Updates the design of the drawer to accommodate an ad (or other content) above the nav.
- Adds new variables to configure the header for fDi
- text-hover-color
- drawer-background
- drawer-button-background
- drawer-text-hover-color
- drawer-nav-hover-background
- Adds support to switch to the drawer at a custom breakpoint
- Removes some tests. These did not work, I'd like to improve our test coverage separately. More details below.
**Example fDi Config**
To test an FDi-like design, temporarily replace brand config for the internal brand:
```scss
@if oBrandGetCurrentBrand() == 'internal' {
$fdi-blue: #1173C1;
$background-grey: #ECECEC;
$fdi-border: #979797;
@include oBrandDefine('o-header-services', 'internal', (
'variables': (
logo: null,
top-text: oColorsGetPaletteColor('black'), …
```
=> Update brand configuration and drawer design

README.md, main.scss
- Not all available brand variables are documented in the code, they're their to customise the whitelabel brand, so add them to the readme explicitly.
- The `drawer-breakpoint` option was only documented in the readme. This documents in in codedocs too.
=> Improve documentation

MIGRATION.md
Change V2 to V3.
I think this is right! I don't think it reads correctly otherwise?
=> Correction in migration guide

MIGRATION.md
The example as given doesn't work for me
Diff is a bit noisy, but all I've done is move the nav inside the header, rather than as the next sibling
=> fix nav position in html order

README.md
Code copied from this failed to compile using `dart-sass`, with this unhelpful error:
```
ERROR in ./src/app.scss (./node_modules/css-loader/dist/cjs.js??ref--4-1!./node_modules/postcss-loader/src??postcss!./node_modules/sass-loader/lib/loader.js??ref--4-3!./src/app.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
$opts: types:
^
Expected ")".
╷
13 │     $opts: types:
│                 ^
╵
src/styles/_header.scss 13:14  root stylesheet
stdin 27:9                     root stylesheet
```
=> Add brackets around example $opts maps

src/js/drawer.js
>If the element is hidden (for example, by setting style.display on the element or one of its ancestors to "none"), then 0 is returned.
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetHeight
=> Correct primary nav visibility on deskop.

src/scss/_drop-down.scss, src/scss/_top.scss
Use `oTypographySans` over `oTypographySize` as this supports progressive font loading. Related o-typography issue: https://github.com/Financial-Times/o-typography/issues/184
Before:
After (note the title jumps in size significantly less):
=> Improve progressive font loading.

demos/src/header.mustache, origami.json, src/js/drawer.js
Builds on (please review first): https://github.com/Financial-Times/o-header-services/pull/97
Relates to this issue: https://github.com/Financial-Times/o-header-services/pull/97
When related content is used without a primary nav, they become 
squashed and unformatted on mobile viewports instead of being 
hidden as with the previous major v2 (to be shown behind the draw).
This PR enables related content to be behind a drawer on mobile
when there is no primary nav. Note: it requires a burger element.
=>  Fix mobile experience for headers with related content.

README.md, demos/src/header.mustache, main.scss, origami.json, src/js/drawer.js, src/scss/_drawer.scss, src/scss/_primary-nav.scss, src/scss/_secondary-nav.scss, src/scss/_top.scss
The core experience of o-header-services is a little broken.
- There's a flash of the drawer as the JS loads on each page.
- The drop down is detatched from the menu item when items are
on multiple lines (due to the drawer not initalising).
- The scroll arrows show even though they don't work.
This PR restores the core behavior of the previous major
version (v2):
- Hide primary nav items for the core experience when they
should be behind the drawer. There should be a fallback
provided using the hamburger's anchor. This behavior is
consistent with the demos and previous major (v2), I've
reinstated our [previous recommendations](https://github.com/Financial-Times/o-header-services/tree/v2.3.4#core-experience-of-the-drawer) to the README.
- Hide the scroll arrows within the secondary nav for …
=> Prevent flash of the drawer on mobile.

src/js/drawer.js, src/js/drop-down.js, src/js/header.js
This addressed https://github.com/Financial-Times/o-header-services/issues/106.
The Dropdown checks if the drawer is enabled by looking for a CSS
class. The Drawer adds the CSS class when it should be enabled.
There was a race condition, where the Drawer would add the class
on resize with a debounced event listener after the Dropdown
has checked for the class.
This PR adds a debounce to the Dropdown resize for performance
purposes, but a race condition could still exist. So the Drawer
is passed to the Dropdown so the Dropdown may check the status
of the Drawer directly without an implicit dependency.
There is a "flash" during the transition as the nav item still
animates -- this is a [separate issue](https://github.com/Financial-Times/o-header-services/issues/107).
=> Fix drawer/dropdown race condition.

src/scss/_drawer.scss, src/scss/_drop-down.scss, src/scss/_variables.scss
The dropdown transitions down from above its nav item, so it
appears to come from the nav item. The nav item has a higher
z-index so the dropdown does not obscure the button and appears to
come from behind or within.
As the nav item had a higher z-index than their dropdown, when
nav items end up on two rows the dropdown from items in the
first row are hidden by the second.
Removing the z-index from the nav items fixes this but leaves
a small visual oddity as the dropdown transitions. To improve
this for modern browsers I've added a clip-path (clip with
greater browser support does not allow percentages).
Resolves: https://github.com/Financial-Times/o-header-services/issues/105
Without the clip path:
With the clip path:
=> Use clip-path over z-index to hide animating dropdown.

src/js/drawer.js, test/js/drawer.test.js
The class `o-header-services__primary-nav--open` has no effect
if the draw is not enabled.
=> Do not add redundant `o-header-services__primary-nav--open` class

origami.json, src/js/drop-down.js, src/scss/_drop-down.scss, test/js/drop-down.test.js
Fixes: https://github.com/Financial-Times/o-header-services/issues/107
Relates to Slack conversion:
https://financialtimes.slack.com/archives/C02FU5ARJ/p1585319930024200
gif of before, note the drop down flash when transitioning to a desktop view:
=> Prevent dropdown "flash" when drawer is enabled/disabled on resize.

test/js/drawer.test.js, test/js/drop-down.test.js, test/js/header.test.js
Stop using the magic imports for proclaim and sinon and pull them from the global because that's where Karma has added them. This is required for obt v10 to be released.
=> Stop using magic webpack imports

demos/src/header.mustache
o-header-services has a visually hidden item within dropdown menus to
close the dropdown. The close button was a direct child of the
dropdown `ul` list, which is not valid. It is now nested within a
list item `li`.
Users of o-header-services will need to update markup accordingly.
Fixes: https://github.com/Financial-Times/o-header-services/issues/142
=> Add a missing `li` element in dropdown navigation demo.

src/scss/_drawer.scss, src/scss/_drop-down.scss
Fixes: https://github.com/Financial-Times/o-header-services/issues/150
=> Correct dropdown border style within the drawer

main.js, src/js/header.js, test/js/drawer.test.js, test/js/drop-down.test.js, test/js/header.test.js
relative imports require the full path including the extension because browsers use the import name to make a network request and they do not implicitly add a .js file extension if one is missing
=> add extension to relative imports to make the code work directly in a browser

README.md, demos/src/main.js, demos/src/pa11y.mustache, origami.json, src/js/drawer.js, src/js/drop-down.js, src/js/header.js, src/js/scroll.js, src/scss/_drop-down.scss, src/scss/_primary-nav.scss, src/scss/_secondary-nav.scss, test/js/drop-down.test.js
- Hide focusable elements in collapsed dropdown menus (Fixes https://github.com/Financial-Times/o-header-services/issues/152)
- Include dropdowns in pa11y check (relates to https://github.com/Financial-Times/o-header-services/issues/152)
- Improve the focus state of dropdown nav items
- Update JSDoc/parameter names
- Replace use of document `core` class (the core/enhanced classes are not part of the spec and components
should work independently)
=> Hide focusable elements in collapsed dropdown menus

src/js/drop-down.js, test/js/drop-down.test.js
If the dropdown close button at the end of the dropdown menu
is clicked it will not close the menu if the menu has the current
page within it and the drawer is open.
=> Fix the hidden close button in the drawer.
